# Generated by Django 4.0.1 on 2022-06-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='product_tax',
        ),
    ]
